### ISSUE TITLE
Move inline documentation to README.MD

### ISSUE THREAD

**Issue by ferndot** [joshua-s/prow.js#1]
There is currently function documentation in the code. It would be nice to move this to the README.MD file.

The README.MD should also include an example of how to include prow.js in a project.

I am available to assist if you have any questions!

**Comment by ronitshar** [comment]
I can do this! However to include prow.js in any project, you should publish it as a package on npm.

**Comment by ferndot** [comment]
@juniorvid Sweet, thanks!

That is a great idea. I will investigate it.

**Comment by ronitshar** [comment]
#2 I'm done! Look it over and if you like it, could you please merge my pull request? Thanks!

**Comment by ferndot** [comment]
@juniorvid thanks for the help! I merged it.
